### ISSUE TITLE
the performance when using some filters (USM) is not good

### ISSUE THREAD

**Issue by mygmyg** [Tencent/DVQA#10]
when i test it on a video using unsharp mask filter, the mos is better, but the value of dqva is lower,the value of vmaf is higher;  may be caused by the training data(more likely), or by the network (the use of residual frames);

any solution for prefilter or postprefilter?

**Comment by tommyhq** [comment]
This is a known issue. I am also interested in this problem. There are several possible reasons:

1. Current training data involves only H.264 compression on PGC reference, without any pre- or post-filtering. 
2. Things get complicated when enhancement is in the pipeline.
3. I am not sure whether your test video is UGC or PGC. The trained model might not perform well on UGC sequences. 

We are considering to develop new models to deal with UGC pre-processed with unsharp filter (FFMPEG), as well as UGC compressed with H.264 encoder.

It takes time as we have to do everything from scratch, i.e. test sequences, subjective data, model tweaking, etc.
