### ISSUE TITLE
The MOS provided is subjectively collected or pseudo ?

### ISSUE THREAD

**Issue by Sissuire** [Tencent/DVQA#2]
Very grateful the release of `DVQA`.

It seems that the provided dataset is from `JND-VideoSet`. But clearly `VideoSet` just provides the JND threshold to my knowledge. So, the MOS provided here is a subjectively collected result from experiment ? or a pseudo one with some tricks?

**Comment by tommyhq** [comment]
Yes. The provided **subjective** score is `SUR` (Satisfied User Ratio) , which is derived from `JND-VideoSet`. Traditional MOS score is  in a scale of [1, 5] and 1 for worst and 5 for best. However, 'SUR' is defined in a different way.

VideoSet contains JND samples in terms of QP values. SUR is defined as SUR = 1 - CDF(JND) along the QP axis. Clearly, it gives the percentage of users that are unable to tell the difference between reference and distorted videos.

`SUR` is mentioned in Section 7 of [VIdeoSet](https://www.sciencedirect.com/science/article/pii/S1047320317300950) and explicitly defined in Section 2 of [SUR prediction](https://ieeexplore.ieee.org/abstract/document/8461571).

**Comment by Sissuire** [comment]
@tommyhq Thanks. So, you presumed that videos at the 1st JND share a same quality score.

**Comment by tommyhq** [comment]
@Sissuire I am not clear about your concern. 

Note that SUR has nothing to do with the 75% JND location. It uses all raw JND samples.

On the other hand, we got 1 JND sample from 1 volunteer during subjective test. That JND location is the boundary between perceptual lossless and lossy (with high probability), for that specific volunteer. Thus, it is assumed that the quality of the 1st JND (raw samples) is well aligned.

**Comment by Sissuire** [comment]
@tommyhq Thank you for the helpful reply, which havs resolved my doubt.
