### ISSUE TITLE
Could you provide the download link of video quality datasets?

### ISSUE THREAD

**Issue by harlanc** [Tencent/DVQA#3]
There are so many datasets on the official website, which one do you use for test? Thank you.

http://live.ece.utexas.edu/research/Quality/index.htm

**Comment by tommyhq** [comment]
We use LIVE video quality dataset for test. The link is https://live.ece.utexas.edu/research/Quality/live_video.html. Please follow their instructions to get download link and credentials.

**Comment by harlanc** [comment]
Thanks , does DVQA have a group like WeChat or QQ to do some discussions?

**Comment by tommyhq** [comment]
Please add WeChat account `allienhq` and I will invite you to the discussion group.
