### ISSUE TITLE
训练一个自己的DVQA模型，理想的样本数量是多少？

### ISSUE THREAD

**Issue by harlanc** [Tencent/DVQA#4]
包括，训练集合 验证集 测试集。谢谢

**Comment by tommyhq** [comment]
Sorry, I don't have answer to this question. It depends on two many factors, video content variety, operating quality range, subjective test methodology, standard deviation of subjective score, etc. 

BTW, please try to communicate in english.

**Comment by harlanc** [comment]
thank you.
