### ISSUE TITLE
The file（.json） about the dataset information of the LIVE and CSIQ

### ISSUE THREAD

**Issue by liu0527aa** [Tencent/DVQA#6]
I want to test the code.However，it's need a long time to edit this.Can you updownload the file （.json）about the dataset information of the LIVE and CSIQ ？Thanks very much.

**Comment by tommyhq** [comment]
Sure. I will upload those two datasets soon.

**Comment by tommyhq** [comment]
I have uploaded the scripts to make json dataset. One needs to specify the test scene names and run it.
