### ISSUE TITLE
could you introduce some about the dataset size, training environments, training speed  

### ISSUE THREAD

**Issue by icegomic** [Tencent/DVQA#8]
could you introduce some about the dataset size, training environments, training speed

**Comment by tommyhq** [comment]
> could you introduce some about the dataset size

There are 3422 distorted videos in the training set. These clips were compressed from 176 references, constant QP in range [8, 47].  Clips with extremely small or large QP are discarded for training.

> training environments

The code is developed with PyTorch 1.4.0, Python 3.5.6, cuda 9.0
> training speed

It takes almost a week to train for 100 epochs with 4 P40 GPU.

**Comment by icegomic** [comment]
> > could you introduce some about the dataset size
> 
> There are 3422 distorted videos in the training set. These clips were compressed from 176 references, constant QP in range [8, 47]. Clips with extremely small or large QP are discarded for training.
> 
> > training environments
> 
> The code is developed with PyTorch 1.4.0, Python 3.5.6, cuda 9.0
> 
> > training speed
> 
> It takes almost a week to train for 100 epochs with 4 P40 GPU.

Very thanks for your details!
