### ISSUE TITLE
How to use it by CPU?

### ISSUE THREAD

**Issue by liu0527aa** [Tencent/DVQA#9]
I have prepared the envirionment.But I want to use by CPU.Could you tell me or add the way about how to use it by CPU instead of GPU

**Comment by tommyhq** [comment]
We recommend the following way to disable GPU. Modify 
`device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")` 
to 
`device = torch.device("cpu")` 
and remove  multiple GPU option in your command line
`--multi_gpu ` 

I believe you know it is much slower to run it on CPU.
